### ISSUE TITLE
JWT module Algorithm not supported

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/badsecrets#42]
File "/jwt/api_jws.py", line 88, in get_algorithm_by_name
    return self._algorithms[alg_name]
KeyError: 'http://www.w3.org/2001/04/xmldsig-more#hmac-sha256'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/jwt/api_jws.py", line 295, in _verify_signature
    alg_obj = self.get_algorithm_by_name(alg)
  File "/jwt/api_jws.py", line 94, in get_algorithm_by_name
    raise NotImplementedError("Algorithm not supported") from e
NotImplementedError: Algorithm not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/bbot/bbot/scanner/manager.py", line 306, in catch
    ret = callback(*args, **kwargs)
  File "/root/bbot/bbot/modules/badsecrets.py", line 30, in handle_event
    r_list = carve_all_modules(body=resp_body, cookies=resp_cookies)
  File "*/badsecrets/base.py", line 136, in carve_all_modules
    r_list = x.carve(**kwargs)
  File "*/badsecrets/base.py", line 97, in carve
    r = self.carve_to_check_secret(s)
  File "*/badsecrets/base.py", line 59, in carve_to_check_secret
    r = self.check_secret(s.groups()[0])

**Comment by liquidsec** [comment]
fixed in https://github.com/blacklanternsecurity/badsecrets/pull/51
