### ISSUE TITLE
bad CLI input not handled gracefully

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/badsecrets#70]
```
Traceback (most recent call last):
  File "/home/liquid/.local/bin/badsecrets", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/liquid/.local/lib/python3.11/site-packages/badsecrets/examples/cli.py", line 233, in main
    hashcat_candidates = hashcat_all_modules(*args.product)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: hashcat_all_modules() takes 1 positional argument but 2 were given
```
input: `badsecrets zzzz KLox5XeGYfb7Lo8zFzr1YepUagXuixcxX55lpFht+rrW6VGheZi831vdusH6DCMfxIhsLG1EPU3OuPvqN2XBc/fj0ew15TQ1zBmmKWJVns4=`

**Comment by liquidsec** [comment]
fixed in https://github.com/blacklanternsecurity/badsecrets/pull/79
