### ISSUE TITLE
rails_secretkeybase poor error handling

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/badsecrets#77]
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/user/..cache/pypoetry/virtualenvs/bbot-IFSyk-JB-py3.10/lib/python3.10/site-packages/badsecrets/base.py", line 188, in carve_all_modules
    r_list = x.carve(**kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/bbot-IFSyk-JB-py3.10/lib/python3.10/site-packages/badsecrets/base.py", line 92, in carve
    r = self.check_secret(v)
  File "/home/user/.cache/pypoetry/virtualenvs/bbot-IFSyk-JB-py3.10/lib/python3.10/site-packages/badsecrets/modules/rails_secretkeybase.py", line 70, in check_secret
    r = self.rails(rails_cookie, secret_key_base)
  File "/home/user/.cache/pypoetry/virtualenvs/bbot-IFSyk-JB-py3.10/lib/python3.10/site-packages/badsecrets/modules/rails_secretkeybase.py", line 36, in rails
    encrypted_data = base64.b64decode(data).decode()
  File "/usr/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```
Also same line:
```
binascii.Error: Invalid base64-encoded string: number of data characters (73) cannot be 1 more than a multiple of 4
```

```

**Comment by liquidsec** [comment]
fixed in https://github.com/blacklanternsecurity/badsecrets/pull/78
